version = 0.1
[default]
profile = "serverless"
region = "ap-northeast-1"

[default.deploy.parameters]
stack_name = "quarkus-quinoa-sample"
resolve_s3 = true
s3_prefix = "quarkus-quinoa-sample"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
